use std::cmp::Ordering;

use super::{Entry, Mapper};

pub struct FileGenerator {
    pub mappers: Vec<Box<dyn Mapper>>,
}

impl FileGenerator {
    pub fn generate_file(&self) -> String {
        let mut lines: Vec<String> = Vec::new();
        lines.append(&mut Self::disclaimer());

        for mapper in &self.mappers {
            if mapper.entries().is_empty() {
                continue;
            }

            lines.push(format!("# {}", mapper.name()));
            lines.append(&mut Self::to_sorted_lines(&mapper.entries()));
            lines.push("".to_owned());
        }

        lines.join("\n")
    }

    pub fn disclaimer() -> Vec<String> {
        [
            "# STOP! - DO NOT EDIT THIS FILE MANUALLY",
            "# This file was automatically generated by \"bin/codeownership validate\".",
            "#",
            "# CODEOWNERS is used for GitHub to suggest code/file owners to various GitHub",
            "# teams. This is useful when developers create Pull Requests since the",
            "# code/file owner is notified. Reference GitHub docs for more details:",
            "# https://help.github.com/en/articles/about-code-owners",
            "",
            "",
        ]
        .iter()
        .map(|line| line.to_string())
        .collect()
    }

    fn to_sorted_lines(entries: &[Entry]) -> Vec<String> {
        let mut lines: Vec<String> = entries.iter().map(|entry| entry.to_row()).collect();
        lines.sort_by(compare_lines);
        lines
    }
}

pub fn compare_lines(a: &String, b: &String) -> Ordering {
    let path_a = extract_path(a);
    let path_b = extract_path(b);

    let mut comps_a = path_a.split('/');
    let mut comps_b = path_b.split('/');

    loop {
        match (comps_a.next(), comps_b.next()) {
            (None, None) => return a.cmp(b),
            (None, Some(_)) => return Ordering::Less,
            (Some(_), None) => return Ordering::Greater,
            (Some(ca), Some(cb)) => match compare_component(ca, cb) {
                Ordering::Equal => continue,
                ord => return ord,
            },
        }
    }
}

fn extract_path(line: &str) -> &str {
    let stripped = line.strip_prefix("# ").unwrap_or(line);
    stripped.split_once(' ').map(|(p, _)| p).unwrap_or(stripped)
}

fn compare_component(a: &str, b: &str) -> Ordering {
    match (a == "**", b == "**") {
        (true, true) => Ordering::Equal,
        (true, false) => Ordering::Less,
        (false, true) => Ordering::Greater,
        (false, false) => a.cmp(b),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_to_sorted_lines_with_special_characters() {
        // The `(` character is less than `*` in the default sort order.
        let mut illustrate_issue = vec!["*".to_string(), "(".to_string()];
        illustrate_issue.sort();
        assert_eq!(illustrate_issue, vec!["(".to_string(), "*".to_string()]);

        let entries = vec![
            Entry {
                // Problem is when a dir name starts with `(`.
                path: "directory/owner/(my_folder)/**/**".to_string(),
                github_team: "@foo".to_string(),
                team_name: "footeam".to_string(),
                disabled: false,
            },
            Entry {
                // Another example of a dir starting with `(`.
                path: "directory/owner/(my_folder)/without_glob".to_string(),
                github_team: "@zoo".to_string(),
                team_name: "zooteam".to_string(),
                disabled: false,
            },
            Entry {
                // And is compared to a glob that starts with `*`.
                path: "directory/owner/**".to_string(),
                github_team: "@bar".to_string(),
                team_name: "barteam".to_string(),
                disabled: false,
            },
            Entry {
                path: "directory/owner/my_folder/**".to_string(),
                github_team: "@baz".to_string(),
                team_name: "bazteam".to_string(),
                disabled: false,
            },
            Entry {
                path: "directory/**".to_string(),
                github_team: "@bop".to_string(),
                team_name: "bopteam".to_string(),
                disabled: false,
            },
        ];
        let sorted = FileGenerator::to_sorted_lines(&entries);
        assert_eq!(
            sorted,
            vec![
                "/directory/** @bop",
                "/directory/owner/** @bar",
                "/directory/owner/(my_folder)/**/** @foo",
                "/directory/owner/(my_folder)/without_glob @zoo",
                "/directory/owner/my_folder/** @baz"
            ]
        );
    }

    #[test]
    fn test_basic_sorting() {
        let entries = vec![
            Entry {
                path: "b_directory/owner/**".to_string(),
                github_team: "@bar".to_string(),
                team_name: "barteam".to_string(),
                disabled: false,
            },
            Entry {
                path: "a_directory/owner/**".to_string(),
                github_team: "@foo".to_string(),
                team_name: "footeam".to_string(),
                disabled: false,
            },
        ];
        let sorted = FileGenerator::to_sorted_lines(&entries);
        assert_eq!(sorted, vec!["/a_directory/owner/** @foo", "/b_directory/owner/** @bar"]);
    }

    #[test]
    fn test_sorting_with_mixed_case() {
        let entries = vec![
            Entry {
                path: "directory/Owner/**".to_string(),
                github_team: "@bar".to_string(),
                team_name: "barteam".to_string(),
                disabled: false,
            },
            Entry {
                path: "directory/owner/**".to_string(),
                github_team: "@foo".to_string(),
                team_name: "footeam".to_string(),
                disabled: false,
            },
        ];
        let sorted = FileGenerator::to_sorted_lines(&entries);
        assert_eq!(sorted, vec!["/directory/Owner/** @bar", "/directory/owner/** @foo"]);
    }

    #[test]
    fn test_sorting_with_numbers() {
        let entries = vec![
            Entry {
                path: "directory/owner1/**".to_string(),
                github_team: "@foo".to_string(),
                team_name: "footeam".to_string(),
                disabled: false,
            },
            Entry {
                path: "directory/owner2/**".to_string(),
                github_team: "@bar".to_string(),
                team_name: "barteam".to_string(),
                disabled: false,
            },
        ];
        let sorted = FileGenerator::to_sorted_lines(&entries);
        assert_eq!(sorted, vec!["/directory/owner1/** @foo", "/directory/owner2/** @bar"]);
    }

    #[test]
    fn test_compare_lines_is_antisymmetric_for_shared_double_star_prefix() {
        let a = "/foo/**/*bar* @org/example-team".to_string();
        let b = "/foo/**/baz/**/* @org/example-team".to_string();

        assert_eq!(compare_lines(&a, &b), Ordering::Less);
        assert_eq!(compare_lines(&b, &a), Ordering::Greater);

        let mut forward = vec![a.clone(), b.clone()];
        let mut reverse = vec![b.clone(), a.clone()];
        forward.sort_by(compare_lines);
        reverse.sort_by(compare_lines);
        assert_eq!(forward, reverse);
        assert_eq!(forward, vec![a, b]);
    }

    #[test]
    fn test_compare_lines_total_order_across_special_character_set() {
        let lines = vec![
            "/directory/** @bop".to_string(),
            "/directory/owner/** @bar".to_string(),
            "/directory/owner/(my_folder)/**/** @foo".to_string(),
            "/directory/owner/(my_folder)/without_glob @zoo".to_string(),
            "/directory/owner/my_folder/** @baz".to_string(),
        ];
        for x in &lines {
            assert_eq!(compare_lines(x, x), Ordering::Equal);
            for y in &lines {
                if x == y {
                    continue;
                }
                let xy = compare_lines(x, y);
                let yx = compare_lines(y, x);
                assert_eq!(xy.reverse(), yx, "asymmetric for {x:?} vs {y:?}");
            }
        }
    }

    #[test]
    fn test_compare_lines_ignores_disabled_comment_prefix() {
        let enabled = "/foo/owner/** @bar".to_string();
        let disabled = "# /foo/owner/** @bar".to_string();
        let other = "/foo/owner/(extra)/file @baz".to_string();

        assert_eq!(compare_lines(&enabled, &other), compare_lines(&disabled, &other));
        assert_eq!(compare_lines(&other, &enabled), compare_lines(&other, &disabled));
    }

    #[test]
    fn test_sorting_with_special_characters() {
        let entries = vec![
            Entry {
                path: "directory/owner-1/**".to_string(),
                github_team: "@foo".to_string(),
                team_name: "footeam".to_string(),
                disabled: false,
            },
            Entry {
                path: "directory/owner_2/**".to_string(),
                github_team: "@bar".to_string(),
                team_name: "barteam".to_string(),
                disabled: false,
            },
        ];
        let sorted = FileGenerator::to_sorted_lines(&entries);
        assert_eq!(sorted, vec!["/directory/owner-1/** @foo", "/directory/owner_2/** @bar"]);
    }
}
