use indoc::indoc;
use predicates::prelude::*;
use std::error::Error;

mod common;
use common::OutputStream;
use common::run_codeowners;

#[test]
fn test_validate_with_custom_executable_name() -> Result<(), Box<dyn Error>> {
    // When executable_name is configured, error should show that command
    run_codeowners(
        "custom_executable_name",
        &["validate"],
        false,
        OutputStream::Stdout,
        predicate::str::contains("Run `bin/codeownership validate`"),
    )?;
    Ok(())
}

#[test]
fn test_validate_with_default_executable_name() -> Result<(), Box<dyn Error>> {
    // When executable_name is not configured, error should show default "codeowners"
    run_codeowners(
        "default_executable_name",
        &["validate"],
        false,
        OutputStream::Stdout,
        predicate::str::contains("Run `codeowners generate`"),
    )?;
    Ok(())
}

#[test]
fn test_custom_executable_name_full_error_message() -> Result<(), Box<dyn Error>> {
    // Verify the complete error message format with custom executable
    run_codeowners(
        "custom_executable_name",
        &["validate"],
        false,
        OutputStream::Stdout,
        predicate::eq(indoc! {r#"

    CODEOWNERS out of date. Run `bin/codeownership validate` to update the CODEOWNERS file
    The following changes are required (- current, + expected):
    -# This file was automatically generated by "codeowners".
    +# This file was automatically generated by "bin/codeownership validate".
    -# Outdated content to trigger validation error
    -/app/old.rb @FooTeam
    +
    +# Annotations at the top of file
    +/app/foo.rb @FooTeam
    +
    +# Team-specific owned globs
    +/ruby/app/payments/** @PaymentTeam
    +
    +# Team YML ownership
    +/config/teams/foo.yml @FooTeam
    +/config/teams/payments.yml @PaymentTeam

    "#}),
    )?;
    Ok(())
}

#[test]
fn test_default_executable_name_full_error_message() -> Result<(), Box<dyn Error>> {
    // Verify the complete error message format with default executable
    run_codeowners(
        "default_executable_name",
        &["validate"],
        false,
        OutputStream::Stdout,
        predicate::eq(indoc! {r#"

    CODEOWNERS out of date. Run `codeowners generate` to update the CODEOWNERS file
    The following changes are required (- current, + expected):
    -# This file was automatically generated by "codeowners".
    +# This file was automatically generated by "bin/codeownership validate".
    -# Outdated content to trigger validation error
    -/app/old.rb @BarTeam
    +# Annotations at the top of file
    +/app/bar.rb @BarTeam
    +
    +# Team YML ownership
    +/config/teams/bar.yml @BarTeam

    "#}),
    )?;
    Ok(())
}
